name: Update all_data.json

permissions:
  contents: write

on:
  push:
    paths:
      - "data/*.json"  # Trigger only if JSON files in data/ change
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  update-all-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Merge JSON files into all_data.json
        run: |
          import json
          import os

          data_folder = "data"
          output_file = os.path.join(data_folder, "all_data.json")
          merged_data = {}

          # Iterate over all JSON files in the data folder
          for filename in os.listdir(data_folder):
              if filename.endswith(".json") and filename != "all_data.json":
                  with open(os.path.join(data_folder, filename), "r", encoding="utf-8") as f:
                      try:
                          merged_data[filename] = json.load(f)  # Store content under filename key
                      except json.JSONDecodeError:
                          print(f"Skipping invalid JSON: {filename}")

          # Write merged content to all_data.json
          with open(output_file, "w", encoding="utf-8") as f:
              json.dump(merged_data, f, indent=4)

        shell: python

      - name: Get latest commit data
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s -- data/)
          LAST_COMMIT_SHA=$(git log -1 --pretty=format:%h -- data/)
          echo "message=$LAST_COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "sha=$LAST_COMMIT_SHA" >> $GITHUB_ENV

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/all_data.json
          git commit -m "$message ($sha)" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
